baseURL: "https://elliott-xiaowei-zhang.github.io/" 
title: Xiaowei (Elliott) Zhang
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Profile
          url: profile/
          weight: 2
        - name: Research
          url: research/
          weight: 3
        # - name: Talks
        #   url: talks/
        #   weight: 4
        - name: Teaching
          url: teaching/
          weight: 5
        - name: Service
          url: service/
          weight: 6
        - name: Gallery
          url: gallery/
          weight: 7
        - name: Contact
          url: contact/
          weight: 8
        # - name: Blog
        #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #   weight: 6

params:
    description: "This website hosts Xiaowei (Elliott) Zhang's research papers, talks, teaching experience, curriculum vitae, and contact information. "
    author: Xiaowei (Elliott) Zhang
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    fixedHeader: true 
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["profile","reseach","talks","teaching","service","contact"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Xiaowei (Elliott) Zhang
          subtitle: | 
              Hi, welcome to my website 🥳!<br> <br> 
              I am a Ph.D. candidate in Information Systems (IS) at the School of Economics and Management, Tsinghua University, advised by Prof. <a style="color:  var(--linkblue);" href="https://www.sem.tsinghua.edu.cn/info/1210/31859.htm"> Zhijie Lin</a>. 
              I am also a PG visiting student at HKUST Business School, advised by Prof. <a style="color: var(--linkblue);" href="https://isom.hkust.edu.hk/faculty-and-staff/directory/jwang">Jing Wang</a>. 
              My research focuses on digital platforms and artificial intelligence.
          imageUrl: "avatar.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Profile
              url: profile/
            - name: Research
              url: research/
            # - name: Talks
            #   url: talks/
            - name: Teaching
              url: teaching/
            - name: Service
              url: service/
            - name: Gallery
              url: gallery/
            # - name: Contact
            #   url: contact/
            # - name: Archive
            #   url: archive/
            # - name: Blog
            #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          # url: cv.pdf
          url: profile
        - name: Email
          url: contact/
        # - name: Zoom
        #   url: https://www.zoom.us/my/igelfeld
        # - name: Location
        #   url: contact/
        # - name: Office Hours
        #   url: officehours/
        - name: LinkedIn
          url: https://www.linkedin.com/in/xiaowei-elliott-zhang-a07a851b3/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=K7uOUW0AAAAJ&hl=en
        - name: ORCID
          url: https://orcid.org/0009-0006-0650-5140
        - name: ResearchGate
          url: https://www.researchgate.net/profile/Xiaowei-Zhang-51?ev=hdr_xprf
        # - name: GitHub
        #   url: https://github.com/pmichaillat
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        # - name: Twitter
        #   url: https://x.com/pmichaillat
        # - name: Bluesky
        #   url: https://bsky.app/profile/pmichaillat.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Xiaowei (Elliott) Zhang"
      # icon: favicon.ico
      icon: avatar.png
      iconHeight: 20

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2